config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#index"
  resources :pages
  get '/aboutus', to: 'pages#aboutus'
  get '/change', to: 'pages#change'
  get '/new', to: 'pages#new'
  get '/profile', to: 'pages#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email
  devise :database_authenticatable, :registerable, :recoverable, :rememberable

  validates_uniqueness_of :email, :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of :email, :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates :first_name, :presence => true 
  validates :last_name, :presence => true
  validates :mobile, :presence => true, :numericality => true, :length => { :minimum => 10, :maximum => 10 }
  validates :dateofbirth, :presence => true
  validates :city, :presence => true
  validates :country, :presence => true
  validates :zipcode, :presence => true
  validates :address, :presence => true

  validates_confirmation_of :password, :on=>:create
  validates_length_of :password, :within => Devise.password_length, :allow_blank => true

PASSWORD_FORMAT = /\A
  (?=.{8,})          
  (?=.*\d)           
  (?=.*[a-z])        
  (?=.*[A-Z])        
  (?=.*[[:^alnum:]]) 
/x

validates :password, 
  presence: true, 
  length: { in: Devise.password_length }, 
  format: { with: PASSWORD_FORMAT }, 
  confirmation: true, 
  on: :create 

validates :password, 
  allow_nil: true, 
  length: { in: Devise.password_length }, 
  format: { with: PASSWORD_FORMAT }, 
  confirmation: true, 
  on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :first_name, :last_name, :dateofbirth, :mobile, :city, :country, :zipcode, :address, :password])
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :first_name, :last_name, :dateofbirth, :mobile, :city, :country, :zipcode, :address, :current_password)}
        end

    def after_sign_in_path_for(resource)
        root_path
    end
    def new
        respond_to do |format|
          format.html
          format.js
        end
      end
      def change
        respond_to do |format|               
          format.js
        end        
      end 
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :aboutus]
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'pages/nav' %>
    <% if flash[:notice] %>
        <div class="alert alert-success alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= notice %>
        </div>
    <%end%>
    <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible fade show">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= alert %>
        </div>
    <%end%>
    <div class="container">
      <br>
      <%= yield %>
   </div>   
  </div>
</body>
</html>

app/views/pages/_change.html.erb
jQuery is a JavaScript library designed to simplify HTML DOM tree traversal and manipulation, as well as event handling, CSS animation, and Ajax. It is free, open-source software using the permissive MIT License. As of May 2019, jQuery is used by 73% of the 10 million most popular websites.

app/views/pages/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#"><%= link_to "ArtZone", root_path, class: "nav-link" %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
          <%= link_to "Profile", profile_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
         <p class="nav-link" style="color:red;"> <%= link_to('Logout', destroy_user_session_path, :method => :delete, :style => "color:white; text-decoration: none;") %></p>
          </li>
          <% else %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
          <%= link_to "About", aboutus_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  

app/views/pages/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Welcome ArtZone</h4>
</div>
<div class="modal-body">
  Modal content comes here*
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/pages/aboutus.html.erb
<br>
<br>
<h2>About us page</h2>

app/views/pages/change.js.erb
$('#hide-button').hide();
$("#data").prepend('<%= escape_javascript(render :partial => "change") %>');

app/views/pages/index.html.erb
<% if user_signed_in? %>
  <h1>Welcome</h1>
  <h2><%= current_user.first_name %> <%= current_user.last_name %></h2>
  <hr>

  <div id="hide-button">
    <%= link_to "JQuery", change_path, :remote => true, class: 'btn btn-success' %>
  </div>
  <div id="data"></div>
  <br>

  <%= link_to 'Modal', new_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-info'}  %>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
    
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">Welcome to our Site</h1>
        <p>Demo App</p>
        <ul class="list-unstyled">
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal("show");

app/views/pages/profile.html.erb
<center>
  <div id="formContent">
    <%# <div style="width:250px;"> %>
    <h2>Profile</h2>  
    <br>
    <table>
      <tr>
        <th>Name<th>
        <td><%= current_user.first_name %> <%= current_user.last_name %></td>      
      </tr>
      <tr>
        <th>Email<th>
        <td><%= current_user.email %></td>
      </tr>
      <tr>
        <th>DOB<th>
        <td><%= current_user.dateofbirth %></td>      
      </tr>
      <tr>
        <th>Mobile<th>
        <td><%= current_user.mobile %></td>
      </tr>
      <tr>
        <th>City<th>
        <td><%= current_user.city %></td>
      </tr>
      <tr>
        <th>Country<th>
        <td><%= current_user.country %></td>
      </tr>
      <tr>
        <th>Zipcode<th>
        <td><%= current_user.zipcode %></td>
      </tr>
      <tr>
        <th>Address<th>
        <td><%= current_user.address %></td>
    </table>
    <br>
    <%= link_to 'Edit profile', edit_user_registration_path, class: "btn btn-success" %>
    <br>
    <br>
    <br>
</center>